### ISSUE TITLE
Please support reading and writing boot track code

### ISSUE THREAD

**Issue by joshtriplett** [cecton/mbrman#1]
Could you please provide access to read and write the boot track, ideally by exposing a mutable slice?

Thanks for a great library!

**Comment by cecton** [comment]
I did thought of that but I feel that this is just not the role of the lib. But since it's requested 😁 I'll do it!

**Comment by joshtriplett** [comment]
On September 1, 2019 12:24:21 PM PDT, Cecile Tonglet <notifications@github.com> wrote:
>I did thought of that but I feel that this is just not the role of the
>lib. But since it's requested 😁 I'll do it!>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/cecton/mbrman/issues/1#issuecomment-526946191

Doesn't need to have any extra boot-related functionality; I'd just like it to have access rather than treating it like padding. Anything beyond basic read/write is definitely another crate's job. :)

**Comment by cecton** [comment]
@joshtriplett can you check #2 and let me know if it's good for you when you have time?

**Comment by joshtriplett** [comment]
@cecton Done, and thank you!

**Comment by cecton** [comment]
Thanks to you for your interest @joshtriplett
